### PR TITLE
Add citation and DOI links

### LINKED ISSUE #5: Add manuscript citation to the README
* Documentation reference (URL):README.md (or https://ess-dive.gitbook.io/continuous-soil-respiration-reporting-format/)
* Submitter: Charu Varadharajan
* Justification (why is this change necessary?): The README currently has a stub for the paper citation if it was accepted, and should be updated with the final citation

I suggest the following changes:
- Add the doi and final citation of the published data package on ESS-DIVE
- Add the final citation to the published manuscript in Ecological Informatics.

### PR DESCRIPTION
**Pull request by bpbond**
This PR adds manuscript citation info and DOI links.

@robcrystalornelas I was going to add a link to the published data package on ESS-DIVE, per Charu's recommendation, but couldn't find it:

Screen Shot 2021-04-23 at 6 44 26 AM

Thoughts? Thanks.

Closes #5

### CODE REVIEW

**Review by wavingtowaves — APPROVED** [review]
Hi Ben, 
Thanks for adding the manuscript citation--looks great to me.  The data package for the reporting format hasn't been uploaded to ESS-DIVE yet since there are still a few more steps to complete.

@stephpenn1 are there more files we are planning to upload to GitHub before the github repo is considered 'final'?  

After that, we'll tag the v1.0.0 release, then download the whole repo and upload it to ESS-DIVE.

**Comment by bpbond** [comment]
@stephpenn1 ?

**Comment by stephpenn1** [comment]
No more files, I need to go through #3 today and then all will be final. Will ping you when it is.

**Comment by stephpenn1** [comment]
Ok @robcrystalornelas everything is updated and ready. @bpbond feel free to merge whenever

**Comment by wavingtowaves** [comment]
> Ok @robcrystalornelas everything is updated and ready. @bpbond feel free to merge whenever

Great, when Ben merges this branch into main, would you all like me to take the lead on: 
- tagging a v1.0.0 release on GitHub 
- Uploading the content to ESS-DIVE?

**Comment by bpbond** [comment]
@robcrystalornelas @stephpenn1 done! Rob, if you're willing, sure, but not sure about Steph's plans.

**Comment by wavingtowaves** [comment]
> @robcrystalornelas @stephpenn1 done! Rob, if you're willing, sure, but not sure about Steph's plans.

@stephpenn1 Let me know how you'd like to handle the tagging a new version and uploading to ESS-DIVE. I'm happy to discuss further or help however I'm able.

**Comment by stephpenn1** [comment]
@robcrystalornelas I don't have much experience with either. Is the tagging done on Github?

**Comment by wavingtowaves** [comment]
@stephpenn1  Tagging is done on GitHub using the 'create a new release' button you can see in the image below of where the button is located. After clicking that link, you'll have the option to tag the release as v1.0.0 You can see an example of Kim and Alistair's here: https://github.com/ess-dive-community/essdive-leaf-gas-exchange/releases/tag/v1.0

As a side note, I just sent you over an email about the GitHub manuscript I'm hoping to submit today and hoping to get your approval. Thanks Stephanie!

---

Screen Shot 2021-04-30 at 10 58 50 AM

**Pull request merged**
